# Generated by Django 5.1.2 on 2024-12-07 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_carrinho_cliente_alter_produto_carrinho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('endereco_entrega', models.TextField()),
                ('nome_destinatario', models.CharField(max_length=200)),
                ('chave_pacote', models.CharField(blank=True, max_length=10, unique=True)),
                ('data_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Em Processamento', max_length=20)),
                ('carrinho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produtos.carrinho')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
