# Generated by Django 5.1.2 on 2024-12-08 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_pedido_chave_pacote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
